# To configure the workflow:
# - Replace {SOLUTION_PATH} with the name of the solution file in `env` section
# - Uncomment the steps in the `build` job

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "./FastProjects.Data.EntityFrameworkCore.sln"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Set up Docker on supported runners (Linux, Windows)
      - name: Set up Docker on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Set up Docker on Windows
        if: runner.os == 'Windows'
        run: |
          Start-Service docker
          docker --version

      - name: Set up Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          until docker system info; do sleep 1; done

      - name: Verify Docker Installation
        run: docker --version
        
          
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build
